# Generated by Django 5.2.9 on 2026-01-15 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ESCROW_PENDING', 'Escrow Pending'), ('ESCROWED', 'Escrowed'), ('DELIVERED', 'Delivered'), ('RELEASED', 'Released'), ('DISPUTE', 'Dispute')], default='ESCROW_PENDING', max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
