# Generated by Django 5.2.9 on 2026-01-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='000000000000000', max_length=15),
            preserve_default=False,
        ),
    ]
