# Generated by Django 5.2.9 on 2026-01-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_seller_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='clothing', max_length=50),
            preserve_default=False,
        ),
    ]
