# Generated by Django 5.2.9 on 2026-01-16 10:23

import django.db.models.deletion
from django.db import migrations, models
import uuid


def populate_tracking_numbers(apps, schema_editor):
    """Generate unique tracking numbers for existing orders"""
    Order = apps.get_model('shop', 'Order')
    for order in Order.objects.filter(tracking_number=''):
        order.tracking_number = str(uuid.uuid4()).split('-')[0].upper()
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(populate_tracking_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men')], default='men', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
