# Generated by Django 5.2.9 on 2026-01-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_category_delete_customuser_delete_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
